# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 438)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 411, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.widget.setFont(font)
        self.widget.setStyleSheet("border-radius:15px;\n"
                                  "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c94b4b,stop:1 #4b134f);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 11, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;")
        self.label.setObjectName("label")
        self.update_lineEdit_meaning = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_meaning.setGeometry(QtCore.QRect(93, 18, 191, 31))
        self.update_lineEdit_meaning.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_meaning.setObjectName("update_lineEdit_meaning")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 64, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setObjectName("label_2")
        self.update_lineEdit_synonym = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_synonym.setGeometry(QtCore.QRect(93, 70, 191, 31))
        self.update_lineEdit_synonym.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_synonym.setObjectName("update_lineEdit_synonym")
        self.update_lineEdit_antonym = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_antonym.setGeometry(QtCore.QRect(93, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_lineEdit_antonym.setFont(font)
        self.update_lineEdit_antonym.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_antonym.setObjectName("update_lineEdit_antonym")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 115, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;")
        self.label_3.setObjectName("label_3")
        self.update_lineEdit_describe = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_describe.setGeometry(QtCore.QRect(93, 174, 291, 31))
        self.update_lineEdit_describe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_describe.setObjectName("update_lineEdit_describe")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 168, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:none;")
        self.label_5.setObjectName("label_5")
        self.update_lineEdit_example = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_example.setGeometry(QtCore.QRect(93, 226, 291, 31))
        self.update_lineEdit_example.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_example.setObjectName("update_lineEdit_example")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 273, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:none;")
        self.label_6.setObjectName("label_6")
        self.update_lineEdit_group = QtWidgets.QLineEdit(self.widget)
        self.update_lineEdit_group.setGeometry(QtCore.QRect(93, 278, 121, 31))
        self.update_lineEdit_group.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.update_lineEdit_group.setObjectName("update_lineEdit_group")
        self.update_btn_update = QtWidgets.QPushButton(self.widget)
        self.update_btn_update.setGeometry(QtCore.QRect(130, 350, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.update_btn_update.setFont(font)
        self.update_btn_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_btn_update.setStyleSheet("QPushButton{\n"
                                             "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #8A2387, stop:0.5 #E94057, stop:1 #F27121);\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover{\n"
                                             "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ff00cc, stop:1 #333399);\n"
                                             "}")
        self.update_btn_update.setObjectName("update_btn_update")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 316, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: none;")
        self.label_7.setObjectName("label_7")
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setGeometry(QtCore.QRect(380, 10, 21, 21))
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                    "border-radius:10px;")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Meaning:"))
        self.label_2.setText(_translate("MainWindow", "Synonym:"))
        self.label_3.setText(_translate("MainWindow", "Antonym:"))
        self.label_4.setText(_translate("MainWindow", "Describe:"))
        self.label_5.setText(_translate("MainWindow", "Example:"))
        self.label_6.setText(_translate("MainWindow", "Group:"))
        self.update_btn_update.setText(_translate("MainWindow", "Update"))
        self.label_7.setText(_translate("MainWindow", "Notice: You should set number for group."))
